const LUServerMessageType = {
    'MSG_WORLD_CLIENT_VALIDATION': 0x01,
    'MSG_WORLD_CLIENT_CHARACTER_LIST_REQUEST': 0x02,
    'MSG_WORLD_CLIENT_CHARACTER_CREATE_REQUEST': 0x03,
    'MSG_WORLD_CLIENT_LOGIN_REQUEST': 0x04,
    'MSG_WORLD_CLIENT_GAME_MSG': 0x05,
    'MSG_WORLD_CLIENT_CHARACTER_DELETE_REQUEST': 0x06,
    'MSG_WORLD_CLIENT_CHARACTER_RENAME_REQUEST': 0x07,
    'MSG_WORLD_CLIENT_HAPPY_FLOWER_MODE_NOTIFY': 0x08,
    'MSG_WORLD_CLIENT_SLASH_RELOAD_MAP': 0x09,
    'MSG_WORLD_CLIENT_SLASH_PUSH_MAP_REQUEST': 0x0a,
    'MSG_WORLD_CLIENT_SLASH_PUSH_MAP': 0x0b,
    'MSG_WORLD_CLIENT_SLASH_PULL_MAP': 0x0c,
    'MSG_WORLD_CLIENT_LOCK_MAP_REQUEST': 0x0d,
    'MSG_WORLD_CLIENT_GENERAL_CHAT_MESSAGE': 0x0e,
    'MSG_WORLD_CLIENT_HTTP_MONITOR_INFO_REQUEST': 0x0f,
    'MSG_WORLD_CLIENT_SLASH_DEBUG_SCRIPTS': 0x10,
    'MSG_WORLD_CLIENT_MODELS_CLEAR': 0x11,
    'MSG_WORLD_CLIENT_EXHIBIT_INSERT_MODEL': 0x12,
    'MSG_WORLD_CLIENT_LEVEL_LOAD_COMPLETE': 0x13,
    'MSG_WORLD_CLIENT_TMP_GUILD_CREATE': 0x14,
    'MSG_WORLD_CLIENT_ROUTE_PACKET': 0x15,
    'MSG_WORLD_CLIENT_POSITION_UPDATE': 0x16,
    'MSG_WORLD_CLIENT_MAIL': 0x17,
    'MSG_WORLD_CLIENT_WORD_CHECK': 0x18,
    'MSG_WORLD_CLIENT_STRING_CHECK': 0x19,
    'MSG_WORLD_CLIENT_GET_PLAYERS_IN_ZONE': 0x1a,
    'MSG_WORLD_CLIENT_REQUEST_UGC_MANIFEST_INFO': 0x1b,
    'MSG_WORLD_CLIENT_BLUEPRINT_GET_ALL_DATA_REQUEST': 0x1c,
    'MSG_WORLD_CLIENT_CANCEL_MAP_QUEUE': 0x1d,
    'MSG_WORLD_CLIENT_HANDLE_FUNNESS': 0x1e,
    'MSG_WORLD_CLIENT_FAKE_PRG_CSR_MESSAGE': 0x1f,
    'MSG_WORLD_CLIENT_REQUEST_FREE_TRIAL_REFRESH': 0x20,
    'MSG_WORLD_CLIENT_GM_SET_FREE_TRIAL_STATUS': 0x21,
    'MSG_WORLD_CLIENT_TOP_FIVE_ISSUES_REQUEST': 0x22,
    'MSG_WORLD_CLIENT_MAYBE_UGC_DOWNLOAD_FAILED': 0x23,
    'MSG_WORLD_CLIENT_UGC_DOWNLOAD_FAILED': 0x78
};

LUServerMessageType.key = function(value) {
    for( let prop in this ) {
        if( this.hasOwnProperty( prop ) ) {
            if( this[ prop ] === value )
                return prop;
        }
    }
};

module.exports = LUServerMessageType;